[target.'cfg(target_family = "windows")']
rustflags = ["-Cdebuginfo=0", "-Dwarnings"]

[target.x86_64-unknown-linux-gnu]
linker = "/usr/bin/clang"
rustflags = ["-Cdebuginfo=0", "-Dwarnings", "-Clink-arg=-fuse-ld=lld"]